/* v28 - Correção da aba Gestão: tela única independente e clique garantido */
(function(){
  const SCREEN='gestaoUnicaV28';
  const TAB='gestao_barber_tab_v28';
  const hidden=['managementUnifiedV27','managementAdvancedV17','workbookSyncV22','productSalesV21','stockControlV21','billsControlV21','closingDreV21','auditV21','customerRecoveryV26','cloudSync','paymentsCenterV17','packagesCenterV17','onlineBooking','automation','automation100','management'];
  const tabs=[['geral','Visão geral','📌'],['planilha','Planilha','📊'],['produtos','Produtos','🧴'],['estoque','Estoque','📦'],['contas','Contas','🧾'],['dre','DRE / Fluxo','📈'],['auditoria','Auditoria','✅'],['clientes','Recuperar clientes','🎯']];
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
  const n=v=>{try{if(typeof parseStoredNumber==='function')return parseStoredNumber(v)}catch(e){} if(v==null||v==='')return 0;if(typeof v==='number')return isFinite(v)?v:0;let t=String(v).replace(/R\$/gi,'').replace(/\s/g,'');const neg=/\(|-/.test(t);t=t.replace(/[()]/g,'');if(t.includes(',')&&t.includes('.'))t=t.replace(/\./g,'').replace(',','.');else if(t.includes(','))t=t.replace(',','.');const x=Number(t.replace(/[^0-9.]/g,''));return isFinite(x)?(neg?-Math.abs(x):x):0};
  const brl=v=>{try{if(typeof money==='function')return money(v)}catch(e){} return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})};
  const today=()=>new Date().toISOString().slice(0,10);
  const mon=d=>String(d||today()).slice(0,7);
  const dateOf=r=>String(r?.date||r?.Data||r?.data||'').slice(0,10);
  const clientOf=r=>String(r?.clientName||r?.Cliente||r?.client||r?.cliente||'').trim();
  const servOf=r=>String(r?.serviceName||r?.['Serviço']||r?.service||r?.servico||'Serviço').trim();
  const payOf=r=>String(r?.paymentMethod||r?.Pagamento||r?.payment||r?.pagamento||'Não informado').trim()||'Não informado';
  const valOf=r=>n(r?.saleValue??r?.netSale??r?.value??r?.valor??r?.['Venda líquida']??r?.['Valor tabela']??r?.['Valor do Corte (R$)']);
  const records=()=>((window.state&&state.records)||[]).filter(r=>dateOf(r)&&clientOf(r)&&!/cancelado|ausência|ausencia/i.test(String(r.status||r.Status||'')));
  const months=()=>[...new Set(records().map(r=>mon(dateOf(r))))].sort();
  const curMonth=()=>months().pop()||today().slice(0,7);
  const recMonth=(m=curMonth())=>records().filter(r=>mon(dateOf(r))===m);
  const sum=(a,f)=>a.reduce((s,x)=>s+(f?f(x):n(x)),0);
  const group=(a,key,val)=>{const m=new Map();a.forEach(x=>{const k=key(x)||'Sem informação';m.set(k,(m.get(k)||0)+(val?val(x):1))});return [...m.entries()].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value)};
  const uniq=a=>new Set(a.map(norm).filter(Boolean)).size;
  const dObj=d=>new Date(`${String(d||today()).slice(0,10)}T12:00:00`);
  const days=d=>Math.max(0,Math.floor((dObj(today())-dObj(d))/86400000));
  const despesas=(m=curMonth())=>sum(((state&&state.bills)||[]).filter(b=>mon(b.paidDate||b.dueDate||b.date)===m),b=>n(b.paidValue||b.value||b.expectedValue))+sum(((state&&state.expenses)||[]).filter(e=>mon(e.date||e.dueDate)===m),e=>n(e.value||e.amount));
  const produtos=(m=curMonth())=>((state&&state.productSales)||[]).filter(p=>mon(p.date||p.Data)===m);
  const estoque=()=>((state&&state.stockItems)||[]);
  function css(){if($('#v28css'))return;const s=document.createElement('style');s.id='v28css';s.textContent=`.v28hide{display:none!important}.v28tabs{display:flex;gap:10px;flex-wrap:wrap;margin:6px 0 16px}.v28tab{border:1px solid var(--line);border-radius:999px;background:rgba(255,255,255,.06);color:var(--text);padding:10px 13px;font-weight:850;cursor:pointer}.v28tab.active{background:linear-gradient(145deg,#ffe7a8,var(--gold-strong),var(--gold));color:#171007}.v28grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.v28two{display:grid;grid-template-columns:1fr 1fr;gap:14px}.v28card{border:1px solid var(--line);background:rgba(255,255,255,.055);border-radius:22px;padding:16px;box-shadow:var(--shadow-soft)}.v28card h4{margin:0 0 8px}.v28card p{margin:0;color:var(--muted)}.v28k span{display:block;color:var(--muted);font-size:.8rem}.v28k strong{display:block;font-size:1.55rem;margin-top:7px}.v28bars{display:grid;gap:10px}.v28bar{display:grid;grid-template-columns:120px 1fr 88px;gap:10px;align-items:center}.v28bar span{color:var(--muted);font-size:.84rem;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.v28bar i{display:block;height:13px;border-radius:999px;background:linear-gradient(90deg,var(--gold),var(--gold-strong))}.v28bar em{display:block;height:13px;border:1px solid var(--line);border-radius:999px;background:rgba(255,255,255,.07);overflow:hidden}.v28bar b{text-align:right;font-size:.84rem}.v28mini{height:185px;display:flex;align-items:end;gap:8px}.v28col{flex:1;text-align:center;height:100%;display:grid;grid-template-rows:1fr auto;gap:7px}.v28col i{align-self:end;display:block;border-radius:12px 12px 4px 4px;background:linear-gradient(180deg,var(--gold-strong),var(--orange));min-height:5px}.v28col span{color:var(--muted);font-size:.72rem}.v28table{width:100%;border-collapse:collapse}.v28table th,.v28table td{padding:10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}.v28table th{color:var(--muted);font-size:.76rem;text-transform:uppercase;letter-spacing:.05em}.v28badge{display:inline-flex;padding:5px 9px;border-radius:999px;background:rgba(255,211,109,.12);border:1px solid rgba(255,211,109,.25);color:#ffe7a8;font-size:.76rem;font-weight:850}.v28bad{background:rgba(255,104,104,.12);border-color:rgba(255,104,104,.25);color:#ffd1d1}.v28empty{padding:20px;border:1px dashed var(--line);border-radius:18px;color:var(--muted);text-align:center}@media(max-width:1100px){.v28grid,.v28two{grid-template-columns:1fr}.v28bar{grid-template-columns:90px 1fr 70px}}`;document.head.appendChild(s)}
  function nav(){let b=$(`.nav-link[data-screen="${SCREEN}"]`);if(!b){b=document.createElement('button');b.type='button';b.className='nav-link';b.dataset.screen=SCREEN;b.innerHTML='<span>📊</span>Gestão';const before=$('.nav-link[data-screen="clients"]');if(before?.parentElement)before.parentElement.insertBefore(b,before);else $('.nav')?.appendChild(b)}b.classList.remove('v28hide');b.style.display='flex';return b}
  function hideOld(){hidden.forEach(id=>$$(`.nav-link[data-screen="${id}"]`).forEach(b=>{b.classList.add('v28hide');b.style.display='none'}));$$('.nav-link[data-screen]').forEach(b=>{const t=norm(b.textContent);if(['gestao pro','planilha','produtos','estoque','contas','dre fluxo','auditoria','recuperar clientes','nuvem','pagamentos','agendamentos','automacao 100'].includes(t)){b.classList.add('v28hide');b.style.display='none'}});nav()}
  function section(){let s=$('#'+SCREEN);if(!s){s=document.createElement('section');s.id=SCREEN;s.className='screen';s.innerHTML='<div id="gestaoV28"></div>';$('.content')?.appendChild(s)}return s}
  function bars(data,money=false){if(!data.length)return '<div class="v28empty">Sem dados para exibir.</div>';const max=Math.max(1,...data.map(x=>Math.abs(x.value||0)));return `<div class="v28bars">${data.map(x=>`<div class="v28bar"><span>${esc(x.label)}</span><em><i style="width:${Math.max(3,Math.abs(x.value||0)/max*100)}%"></i></em><b>${money?brl(x.value):Math.round(x.value||0)}</b></div>`).join('')}</div>`}
  function mini(data){if(!data.length)return '<div class="v28empty">Sem dados para gráfico.</div>';const max=Math.max(1,...data.map(x=>Math.abs(x.value||0)));return `<div class="v28mini">${data.map(x=>`<div class="v28col"><i style="height:${Math.max(6,Math.abs(x.value||0)/max*100)}%"></i><span>${esc(x.label)}</span></div>`).join('')}</div>`}
  function table(rows,cols){if(!rows.length)return '<div class="v28empty">Sem dados encontrados.</div>';return `<table class="v28table"><thead><tr>${cols.map(c=>`<th>${esc(c[0])}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${typeof c[1]==='function'?c[1](r):esc(r[c[1]])}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
  function base(content){const active=localStorage.getItem(TAB)||'geral';return `<article class="panel wide-panel"><div class="panel-header split-header"><div><p class="eyebrow">Central única</p><h3>Gestão da Barbearia</h3><p class="muted">Tudo em uma tela: planilha, produtos, estoque, contas, DRE, auditoria e recuperação de clientes.</p></div><button type="button" class="secondary-button" data-v28-refresh>Atualizar</button></div><div class="v28tabs">${tabs.map(t=>`<button type="button" class="v28tab ${active===t[0]?'active':''}" data-v28-tab="${t[0]}">${t[2]} ${t[1]}</button>`).join('')}</div>${content}</article>`}
  function geral(){const m=curMonth(),rs=recMonth(m),rev=sum(rs,valOf),cl=uniq(rs.map(clientOf)),exp=despesas(m),prod=sum(produtos(m),p=>n(p.total||p.gross||p.value||p.saleValue)),res=rev+prod-exp,ticket=rs.length?rev/rs.length:0;const daily=group(rs,dateOf,valOf).sort((a,b)=>a.label.localeCompare(b.label)).slice(-15);return `<div class="v28grid"><div class="v28card v28k"><span>Faturamento serviços</span><strong>${brl(rev)}</strong><p>${rs.length} atendimentos</p></div><div class="v28card v28k"><span>Clientes atendidos</span><strong>${cl}</strong><p>No mês ${m}</p></div><div class="v28card v28k"><span>Ticket médio</span><strong>${brl(ticket)}</strong><p>Serviços</p></div><div class="v28card v28k"><span>Resultado estimado</span><strong>${brl(res)}</strong><p>Serviços + produtos - contas</p></div></div><div class="v28two" style="margin-top:14px"><div class="v28card"><h4>Faturamento por dia</h4>${mini(daily.map(x=>({label:x.label.slice(5),value:x.value})))}</div><div class="v28card"><h4>Serviços mais vendidos</h4>${bars(group(rs,servOf,valOf).slice(0,8),true)}</div></div><div class="v28two" style="margin-top:14px"><div class="v28card"><h4>Formas de pagamento</h4>${bars(group(rs,payOf,valOf).slice(0,8),true)}</div><div class="v28card"><h4>Alertas rápidos</h4>${alerts()}</div></div>`}
  function planilha(){const rs=recMonth(), last=records().slice(-8).reverse();return `<div class="v28grid"><div class="v28card v28k"><span>Registros lidos</span><strong>${records().length}</strong><p>Planilha + importações</p></div><div class="v28card v28k"><span>Mês atual</span><strong>${curMonth()}</strong><p>${rs.length} atendimentos</p></div><div class="v28card v28k"><span>Clientes únicos</span><strong>${uniq(rs.map(clientOf))}</strong><p>No mês</p></div><div class="v28card v28k"><span>Receita lida</span><strong>${brl(sum(rs,valOf))}</strong><p>Serviços</p></div></div><div class="v28card" style="margin-top:14px"><h4>Últimos atendimentos lidos</h4>${table(last,[['Data',r=>esc(dateOf(r))],['Cliente',r=>esc(clientOf(r))],['Serviço',r=>esc(servOf(r))],['Pagamento',r=>esc(payOf(r))],['Valor',r=>brl(valOf(r))]])}</div>`}
  function produtosView(){const ps=produtos(), receita=sum(ps,p=>n(p.total||p.gross||p.value||p.saleValue));return `<div class="v28grid"><div class="v28card v28k"><span>Vendas produtos</span><strong>${ps.length}</strong><p>No mês</p></div><div class="v28card v28k"><span>Receita produtos</span><strong>${brl(receita)}</strong><p>Geladeira/revenda</p></div><div class="v28card v28k"><span>Itens em estoque</span><strong>${estoque().length}</strong><p>Cadastrados</p></div><div class="v28card v28k"><span>Estoque baixo</span><strong>${lowStock().length}</strong><p>Repor</p></div></div><div class="v28two" style="margin-top:14px"><div class="v28card"><h4>Produtos mais vendidos</h4>${bars(group(ps,p=>p.productName||p.name||p.produto||'Produto',p=>n(p.total||p.gross||p.value||p.saleValue)).slice(0,8),true)}</div><div class="v28card"><h4>Últimas vendas</h4>${table(ps.slice(-8).reverse(),[['Data',p=>esc(p.date||p.Data||'')],['Produto',p=>esc(p.productName||p.name||p.produto||'Produto')],['Qtd',p=>esc(p.quantity||p.qtd||1)],['Valor',p=>brl(n(p.total||p.gross||p.value||p.saleValue))]])}</div></div>`}
  function lowStock(){return estoque().filter(i=>n(i.currentStock??i.stock??i.quantity)<=n(i.minStock??i.minimum??5)).slice(0,30)}
  function estoqueView(){const lows=lowStock();return `<div class="v28grid"><div class="v28card v28k"><span>Itens cadastrados</span><strong>${estoque().length}</strong><p>Controle de estoque</p></div><div class="v28card v28k"><span>Estoque baixo</span><strong>${lows.length}</strong><p>Prioridade de compra</p></div><div class="v28card v28k"><span>Movimentos</span><strong>${((state&&state.stockMoves)||[]).length}</strong><p>Entradas e saídas</p></div><div class="v28card v28k"><span>Status</span><strong>${lows.length?'Atenção':'OK'}</strong><p>Reposição</p></div></div><div class="v28card" style="margin-top:14px"><h4>Itens para repor</h4>${table(lows,[['Produto',i=>esc(i.name||i.productName||i.produto||'Produto')],['Atual',i=>esc(i.currentStock??i.stock??i.quantity??0)],['Mínimo',i=>esc(i.minStock??i.minimum??5)],['Sugestão',()=>'<span class="v28badge v28bad">Comprar</span>']])}</div>`}
  function contasView(){const bs=((state&&state.bills)||[]), m=curMonth(), rows=bs.filter(b=>mon(b.paidDate||b.dueDate||b.date)===m),total=sum(rows,b=>n(b.paidValue||b.value||b.expectedValue));return `<div class="v28grid"><div class="v28card v28k"><span>Contas no mês</span><strong>${rows.length}</strong><p>${m}</p></div><div class="v28card v28k"><span>Total previsto/pago</span><strong>${brl(total)}</strong><p>Contas cadastradas</p></div><div class="v28card v28k"><span>Vencidas abertas</span><strong>${bs.filter(b=>String(b.status||'').toLowerCase()!=='pago'&&String(b.dueDate||'')<today()).length}</strong><p>Verificar</p></div><div class="v28card v28k"><span>Categoria maior</span><strong>${(group(rows,b=>b.category||b.categoria||'Outros',b=>n(b.paidValue||b.value||b.expectedValue))[0]||{}).label||'-'}</strong><p>Mais impacto</p></div></div><div class="v28two" style="margin-top:14px"><div class="v28card"><h4>Contas por categoria</h4>${bars(group(rows,b=>b.category||b.categoria||'Outros',b=>n(b.paidValue||b.value||b.expectedValue)).slice(0,8),true)}</div><div class="v28card"><h4>Próximas contas</h4>${table(bs.slice().sort((a,b)=>String(a.dueDate||'').localeCompare(String(b.dueDate||''))).slice(0,10),[['Vencimento',b=>esc(b.dueDate||b.date||'')],['Descrição',b=>esc(b.description||b.name||b.descricao||'Conta')],['Valor',b=>brl(n(b.value||b.expectedValue||b.paidValue))],['Status',b=>esc(b.status||'Aberta')]])}</div></div>`}
  function dreView(){const m=curMonth(),rs=recMonth(m),serv=sum(rs,valOf),prod=sum(produtos(m),p=>n(p.total||p.gross||p.value||p.saleValue)),exp=despesas(m),res=serv+prod-exp;return `<div class="v28grid"><div class="v28card v28k"><span>Receita serviços</span><strong>${brl(serv)}</strong></div><div class="v28card v28k"><span>Receita produtos</span><strong>${brl(prod)}</strong></div><div class="v28card v28k"><span>Despesas</span><strong>${brl(exp)}</strong></div><div class="v28card v28k"><span>Resultado</span><strong>${brl(res)}</strong></div></div><div class="v28two" style="margin-top:14px"><div class="v28card"><h4>DRE visual</h4>${bars([{label:'Serviços',value:serv},{label:'Produtos',value:prod},{label:'Despesas',value:exp},{label:'Resultado',value:res}],true)}</div><div class="v28card"><h4>Leitura rápida</h4><p>Resultado estimado = receita de serviços + produtos - contas lançadas. Use isso como painel de decisão, não como contabilidade final.</p><br><p><span class="v28badge ${res>=0?'':'v28bad'}">${res>=0?'positivo':'atenção'}</span></p></div></div>`}
  function clientes(){const map=new Map();records().forEach(r=>{const k=norm(clientOf(r));if(!k)return;const it=map.get(k)||{name:clientOf(r),last:'',count:0,total:0,services:new Map()};it.count++;it.total+=valOf(r);if(dateOf(r)>it.last)it.last=dateOf(r);it.services.set(servOf(r),(it.services.get(servOf(r))||0)+1);map.set(k,it)});return [...map.values()].map(c=>({...c,days:days(c.last),fav:[...c.services.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||'Cabelo'})).filter(c=>c.days>=30).sort((a,b)=>b.days-a.days)}
  function clientesView(){const rows=clientes();return `<div class="v28grid"><div class="v28card v28k"><span>Clientes para recuperar</span><strong>${rows.length}</strong><p>30+ dias sem voltar</p></div><div class="v28card v28k"><span>Potencial estimado</span><strong>${brl(sum(rows.slice(0,30),c=>Math.max(c.total/Math.max(c.count,1),45)))}</strong><p>Top 30</p></div><div class="v28card v28k"><span>Mais antigo</span><strong>${rows[0]?.days||0} dias</strong><p>${esc(rows[0]?.name||'-')}</p></div><div class="v28card v28k"><span>Ação</span><strong>Brinde</strong><p>Dias fracos</p></div></div><div class="v28card" style="margin-top:14px"><h4>Lista de recuperação</h4>${table(rows.slice(0,30),[['Cliente',c=>esc(c.name)],['Última visita',c=>esc(c.last)],['Dias',c=>`<span class="v28badge ${c.days>=60?'v28bad':''}">${c.days}</span>`],['Serviço provável',c=>esc(c.fav)],['Mensagem',c=>`<button class="secondary-button small-button" data-v28-copy="Oi, ${esc(c.name)}! Tudo bem? Aqui é da Barbearia da Taíse. Vi que faz um tempo desde seu último atendimento de ${esc(c.fav)}. Esta semana temos alguns horários e posso reservar um para você com um brinde especial.">Copiar</button>`]])}</div>`}
  function alerts(){const a=[];if(!records().length)a.push(['Sem dados','Sincronize a planilha para aparecerem gráficos.']);if(lowStock().length)a.push(['Estoque baixo',`${lowStock().length} item(ns) precisam de reposição.`]);const inat=clientes().length;if(inat)a.push(['Recuperação',`${inat} cliente(s) estão há mais de 30 dias sem voltar.`]);if(!a.length)a.push(['Tudo certo','Nenhum alerta crítico agora.']);return a.map(x=>`<p><span class="v28badge">${esc(x[0])}</span> ${esc(x[1])}</p>`).join('<br>')}
  function auditoria(){return `<div class="v28two"><div class="v28card"><h4>Alertas</h4>${alerts()}</div><div class="v28card"><h4>Checklist</h4><p>✅ Planilha sincronizada</p><p>✅ Conferir pagamentos pendentes</p><p>✅ Conferir estoque baixo</p><p>✅ Ver clientes para recuperar</p></div></div>`}
  function render(){css();section();hideOld();const t=localStorage.getItem(TAB)||'geral';let html=t==='planilha'?planilha():t==='produtos'?produtosView():t==='estoque'?estoqueView():t==='contas'?contasView():t==='dre'?dreView():t==='auditoria'?auditoria():t==='clientes'?clientesView():geral();$('#gestaoV28').innerHTML=base(html)}
  function open(){render();$$('.screen').forEach(s=>s.classList.remove('active'));section().classList.add('active');$$('.nav-link').forEach(b=>b.classList.remove('active'));nav().classList.add('active');const title=$('#pageTitle');if(title)title.textContent='Gestão';setTimeout(render,100)}
  document.addEventListener('click',e=>{const g=e.target.closest(`[data-screen="${SCREEN}"]`);if(g){e.preventDefault();e.stopPropagation();open();return}const old=e.target.closest('[data-screen="managementUnifiedV27"],[data-screen="managementAdvancedV17"]');if(old){e.preventDefault();e.stopPropagation();open();return}const tb=e.target.closest('[data-v28-tab]');if(tb){localStorage.setItem(TAB,tb.dataset.v28Tab);render();return}if(e.target.closest('[data-v28-refresh]')){render();return}const cp=e.target.closest('[data-v28-copy]');if(cp){navigator.clipboard?.writeText(cp.dataset.v28Copy||'');try{showToast('Mensagem copiada.')}catch(_){}}},true);
  setTimeout(()=>{css();section();hideOld();render()},300);
  setTimeout(()=>{hideOld(); if(document.querySelector('.screen.active')?.id===SCREEN)open()},1500);
  setInterval(hideOld,2500);
})();
